#!/bin/sh

PROMPT="input> "
HISTORY_FILE="${HOME}/.idktw.history"

while true
do
    REPLY=""
    read -p "${PROMPT}"
    if [ -z "${REPLY}" ]
    then
	continue
    fi
    printf "%s\n" ${REPLY} >> ${HISTORY_FILE}
    sdcv "${REPLY}"
    espeak "${REPLY}"
done
